# Generated by Django 5.1.3 on 2024-12-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleBrand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.state')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('profilePicture', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.state')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('rent', models.CharField(max_length=10)),
                ('availability', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.vehiclebrands')),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.vehicletypes')),
            ],
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.userdetails')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.vehicledetails')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('requestStatus', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.userdetails')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalManagement.vehicledetails')),
            ],
        ),
    ]
