# Generated by Django 5.1.3 on 2024-12-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
