# Generated by Django 5.1.3 on 2024-12-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalManagement', '0002_userdetails_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
